BaseURL = "http://bernhardkircher.com/"

title = "Bernhard Kircher"
theme = "hugo-theme-bleak"
pygmentsuseclasses = true
pluralizelisttitles = false

builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"


[params]
Author = "Bernhard Kircher"
#absURL = "http://bernhardkircher.com/"
#cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Bernhard Kircher's Blog"
logo = "/img/logo.png"
#faviconfile = "img/logo.png"
highlightjs = true
lang = "en"
github = "https://github.com/bernhardkircher"
email = "bernhardkircher@gmail.com"
# linkedin = "example"
twitter = "@bernhardkircher"


[menu]
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"

  [[menu.main]]
      name = "About"
      weight = 1
      identifier = "about"
      url = "/about"

  [[menu.main]]
      name = "Blog"
      weight = 2
      identifier = "blog"
      url = "/post"
